### ISSUE TITLE
Uploaded images show visual glitches

### ISSUE THREAD

**Issue by sandreae** [p2panda/meli#37] opened 2023-10-16 11:51 UTC
![Screenshot_20231016-124930](https://github.com/p2panda/meli/assets/24291662/7e838d4e-82f5-4c3a-9080-630695410d92)

There are bands in the left hand side of the "leaf bee" image.

**Comment by adzialocha** [comment] 2024-03-01 23:47
Duplicate of https://github.com/p2panda/meli/issues/18

**Closed** 2024-03-01 23:47 UTC
Labels: bug
